### ISSUE TITLE
read messageObject when iOS app isn't in background 

### ISSUE THREAD

**Issue by Ragazzetto** [mutualmobile/MMWormhole#52]
Hi 
Thank you for your incredible work !
i would like to know if is possible to read the message object send from the watch app when the iOS app isn't in back ground .
For example : the iOS App is closed , i open the watch app and send the message object . 
If is possible, where i must put my listenForMessageWithIdentifier code to read the message object ?
In my appdelegete or in my view controller ?

Thank you so much

Vanni

**Comment by cnstoll** [comment]
If your iPhone app is already running in the background, and you know it is because of something like a background audio or location tracking event, you can just use MMWormhole however you want to and the message will be delivered on the phone. Yay! That's the easy way.

The hard part comes in if you don't know the iPhone app is already running.

In that scenario, you can use the openParentApplication method on WatchKit (watchOS 1), or the WatchConnectivity frameworks' sendMessage API on watchOS 2.

If you want to use the sendMessage API on watchOS 2, we will be providing support for that in MMWormhole 1.3.0 which should ship in the next few days. Check out the MMWormholeSessionMessageTransiting class, and the MMWormholeTransitingTypeSessionMessage for that support.
