### ISSUE TITLE
Xcode 7 build warnings

### ISSUE THREAD

**Issue by rmsutton** [mutualmobile/MMWormhole#62]
Getting the following build warning with Xcode 7 -

/MMWormhole/Source/MMWormholeFileTransiting.m:36:17: Method override for the designated initializer of the superclass '-init' not found

**Comment by HiddenJester** [comment]
I have a fix for this on my fork at https://github.com/HiddenJester/MMWormhole. It's nothing fancy, you just need to provide some sort of implementation of init in MMWormholeFileTransiting.m. My just prints a message saying to not call it and then returns a wormhole that isn't really going to work (because it lacks a valid App Group Identifier).

I could submit a pull request if desired, but I've already got an open PR (see https://github.com/mutualmobile/MMWormhole/pull/53 ) so I wasn't in a hurry to submit this one.

**Comment by rmsutton** [comment]
Thanks, Jester for the prompt reply - It would be great if this fix made it's way into the pod.

**Comment by cnstoll** [comment]
Hey guys, sorry for the delayed response. I'm putting the finishing touches on an Xcode 7 update that will address this. Hoping to have that wrapped up in the next few days.

Thanks,

- Conrad

**Comment by cnstoll** [comment]
Hey guys. This will also go in as part of 1.3.0. Thanks very much for the issue/PR!

**Comment by rmsutton** [comment]
Awesome! Thanks, Conrad.
