### ISSUE TITLE
1.3.0 does not follow semantic versioning

### ISSUE THREAD

**Issue by ndonald2** [mutualmobile/MMWormhole#63]
I was using 1.2.0 in a project built against watchOS 1 (iOS SDK 8.4). For a number of reasons, my company has not yet switched to Xcode 7 and watchOS 2, though we will be in the near future. 

I recently updated our pods, using an optimistic version of MMWormhole ~> 1.1, which updated us from 1.2 to 1.3 and broke our build due to the dependency on WatchConnectivity, which does not exist in the 8.4 SDK.

Proper semantic versioning would dictate that breaking API changes result in a new major version of the library, i.e. 2.0.0. If the version is to remain at 1.3.0 I would suggest that you add in compatibility checks to not use WatchConnectivity when building for an SDK version less than 9.0.

Thanks!

**Comment by cnstoll** [comment]
Eek. Sorry about that.

This one is tricky because the individual source files do have compatibility checks. The issue is CocoaPods trying to drag in the WatchConnectivity framework I believe.

Do you have a proposed solution for fixing it within a 1.3.0 version by updating the pod spec? Otherwise I can't think of another solution besides updating to 2.0.0 and requiring iOS 9.

Thanks,

- Conrad

**Comment by ndonald2** [comment]
Maybe [weak frameworks](https://guides.cocoapods.org/syntax/podspec.html#weak_frameworks) will work? There would still need to be compatibility checks around the `#import` statements for WatchConnectivity though, I think.

**Comment by cnstoll** [comment]
I ended up opting to bump the version to 2.0.0. Ultimately I didn't really want to change the way the library is organized just to fit CocoaPods. I was hoping to avoid changing it to 2.0.0, since the API didn't really change, it was just extended to support a new framework, but I suppose the addition is enough to justify the version bump so I've gone ahead and done it.

Sorry for the lost time Nick, and thanks for pointing this out.
