### ISSUE TITLE
using messageWithIdentifier initializing with transitingType always nil 

### ISSUE THREAD

**Issue by maxgarmar** [mutualmobile/MMWormhole#84]
Hi guys,

I am using your nice library to communicate watchOS and iOS, I did use it before for watchOS 1 and no problems at all, but now trying to handle from watchOS 2 on I am facing something weird. 
If I initialize with:

` self.wormhole = [[MMWormhole alloc] initWithApplicationGroupIdentifier:@"x.x.x.x"
                                                         optionalDirectory:@"x"
                                                            transitingType:MMWormholeTransitingTypeSessionContext];`

and then

`id messageObject = [self.wormhole messageWithIdentifier:@"identifier"];`

the messageObject is nil always when the app is awaking with context even if I opened the app on iOS before and initialize this identifier. Interesting enough is if I open the app on iOS and make a change on this identifier, then the listener is called right and showing me the changes with this code below (so I guess all the configuration is ok for the group ids and so on):

`[self.listeningWormhole listenForMessageWithIdentifier:@"identifier" listener:^(id messageObject) {    
        NSString * var =  messageObject;     
        if (var != nil) {
            NSLog(@"Listening from phone%@", var);
        }  
    }];`

Seems like the initialization with transitionType (If I got it right is the new way for watchOS 2 ) is not reading the value directly but only with the listener. In this case I cannot initialize values, I have to modify and then the listener is called. Your example also does the same for me on my machine.
Perhaps I got it wrong and this new transitionType is only for messaging with listener and to initialize I need the old way of wormhole (traditional one). But then I don't understand why in your example is done like this.

Thanks ! and keep making good things !

Maxi

**Comment by cnstoll** [comment]
Hey Maxi,

There are a few reasons why this might be the case. It's possible that when the watch app starts up, it hasn't yet received an updated "Application Context" from the WatchConnectivity framework. If you want to test this out, just ask the WCSession.defaultSession for the current application context after checking the wormhole's messageWithIdentifier.

If the application context is nil, or it's contents are empty, then that's why the wormhole is returning no value - because nothing has been delivered yet.

If the application context is not nil, and has valid contents...but the wormhole is still returning no value, then I would like to know, because that's definitely a bug :)

Unfortunately it's just kind of hard to tell exactly why without checking WatchConnectivity, because the whole feature is built on WatchConnectivity and there can be a lot of reasons why WatchConnectivity's content hasn't updated yet.

Curious what you find out.

Thanks,

- Conrad

**Comment by maxgarmar** [comment]
Hi @cnstoll,

I am back developing this code again and finally I could make it work on the watch side. Problem was that I was trying to access to the message before activating the session listening.
Interesting now is the watch is working with:

`[self.watchConnectivityWormhole messageWithIdentifier:@"whatever"];`

and also:

`[self.listeningWormhole listenForMessageWithIdentifier:@"shoppingLists" listener:^(id messageObject)]`

so perfect. But again I have exactly the same code like on the watch, on my iOS side and if it is working only with the listener but not with messageWithIdentifier. So the listener is being called when I change something on the watch with a certain identifier, but when I try to access normally to the same identifier through 

`[self.iOSConnectivityWormhole messageWithIdentifier:@"whatever"];`

then is returning nil for the same identifier that was called on the listener. :-O
When I debug your library and get into the code of the method **messageObjectForIdentifier**, I see that this line is returning empty dictionary. Is that ok ?

`NSDictionary *receivedContext = self.session.receivedApplicationContext;`

the session is ok but the received context is empty, if I understand correctly, this context should contain the latest data that I sent from the watch part, right? Am I missing anything ? or misunderstanding ?

I hope you can help my out
Thanks !

Maxi
