### ISSUE TITLE
listen for message with identifier is not working. but message with identifier is working.Help!!

### ISSUE THREAD

**Issue by davamp** [mutualmobile/MMWormhole#85]

**Comment by gbesler** [comment]
I have the same issue

**Comment by cnstoll** [comment]
Hey ya'll. Thanks for the question an apologies for the delay. It looks like the issue is related to how WatchConnectivity's updateApplicationContext method works. If you update the context with identical content it simply doesn't deliver the update because it doesn't think the context has changed. The reason the content hasn't changed in the demo app is because the second press on the same button is still passing the same number into the context.

The solution if you're looking to use one of the WatchConnectivity transiting types for sending messages, and want to guarantee duplicate messages like you're talking about supporting, then change the *Sender*'s transiting type to MMWormholeTransitingTypeSessionMessage. The default, MMWormholeTransitingTypeSessionContext, will most likely not provide the functionality you're looking for. 

```
self.wormhole = [[MMWormhole alloc] initWithApplicationGroupIdentifier:@"group.com.mutualmobile.wormhole"
                                                         optionalDirectory:@"wormhole"
                                                            transitingType: MMWormholeTransitingTypeSessionMessage];
```
